export enum ServiceType {
  MANDATORY = 'MANDATORY',
  PERMANENT = 'PERMANENT',
  VOLUNTEER = 'VOLUNTEER',
  DISCHARGED = 'DISCHARGED',
  CAREER = 'CAREER',
  RESERVE = 'RESERVE',
  RELEASED_NO_RESERVE = 'RELEASED_NO_RESERVE',
}
